############# English navigation ##############

# main menu
[[main]]
name = "About Us"
url = "about/"
weight = 1

[[main]]
name = "Services"
url = "services/"
weight = 2

[[main]]
name = "Contact"
url = "contact/"
weight = 5



# footer menu
# Company section
[[footer_01]]
name = "Company" # This acts as the section title
title = true     # Flag to identify this as a section title
weight = 0       # Lower weight to appear first

[[footer_01]]
name = "Home"
url = "/"
weight = 1

[[footer_01]]
name = "Services"
url = "services/"
weight = 2

[[footer_01]]
name = "About Us"
url = "about/"
weight = 3

[[footer_01]]
name = "Elements"
url = "elements/"
weight = 4

[[footer_01]]
name = "Contacts"
url = "contact/"
weight = 5

[[footer_01]]
name = "Gallery"
url = "gallery/"
weight = 6

[[footer_01]]
name = "Blog"
url = "blog/"
weight = 7

# Services section
[[footer_02]]
name = "Services" # This acts as the section title
title = true      # Flag to identify this as a section title
weight = 0        # Lower weight to appear first

[[footer_02]]
name = "Residential Roof Replacement"
url = "services/residential-roof-replacement/"
weight = 1

[[footer_02]]
name = "Roof Repair & Leak Detection"
url = "services/roof-repair-leak-detection/"
weight = 2

[[footer_02]]
name = "Gutter Installation & Protection"
url = "services/gutter-installation-protection/"
weight = 3

[[footer_02]]
name = "Storm Damage Roof Restoration"
url = "services/storm-damage-roof-restoration/"
weight = 4
